### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by dberma15** [dkogan/gnuplotlib#9] opened 2017-03-13 17:27 UTC
I have installed gnuplotlib using pip install gnuplotlib and when I try to import it I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-899855f1b989>", line 1, in <module>
    import gnuplotlib
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\site-packages\gnuplotlib.py", line 743, in <module>
    features = _getGnuplotFeatures()
  File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\site-packages\gnuplotlib.py", line 726, in _getGnuplotFeatures
    helpstring = subprocess.check_output(['gnuplot', '--help'], stderr=subprocess.STDOUT)
  File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Any idea how to fix this?

**Comment by dkogan** [comment] 2017-03-13 19:01
dberma15 <notifications@github.com> writes:

> I have installed gnuplotlib using pip install gnuplotlib and when I try to import it I get the following error:
>
> ```
> Traceback (most recent call last):
>   File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-899855f1b989>", line 1, in <module>
>     import gnuplotlib
>   File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
>     module = self._system_import(name, *args, **kwargs)
>   File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\site-packages\gnuplotlib.py", line 743, in <module>
>     features = _getGnuplotFeatures()
>   File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\site-packages\gnuplotlib.py", line 726, in _getGnuplotFeatures
>     helpstring = subprocess.check_output(['gnuplot', '--help'], stderr=subprocess.STDOUT)
>   File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 566, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "C:\Users\bermads1\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 958, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified
> ```
>
> Any idea how to fix this?

Hi. I have not attempted this on Windows. The error looks like it can't
find gnuplot. Do you have it installed? Can you run it simply with
"gnuplot"? Is it in your PATH? I have no idea how this works in Windows,
but if you get it working and have patches, we can talk about them.

Thanks
dima

**Comment by dberma15** [comment] 2017-03-13 19:30
Yes. I installed it from here: https://sourceforge.net/projects/gnuplot/?source=typ_redirect 
I can run gnuplot from the install and I added it to the path and there is no change.

**Comment by dkogan** [comment] 2017-03-13 20:50
dberma15 <notifications@github.com> writes:

> Yes. I installed it from here: https://sourceforge.net/projects/gnuplot/?source
> =typ_redirect
> I can run gnuplot from the install and I added it to the path and there is no
> change.

Well, between the two of us you're the Windows user, so you're going to
have to debug this. Sorry I can't be more help. Good luck.

**Comment by mietzen** [comment] 2018-05-14 09:36
Same on Mac OSX 10.13.4
```
import subprocess
import re

helpstring = subprocess.check_output(['gnuplot', '--help'],
                                        stderr=subprocess.STDOUT,
                                        env={'DISPLAY': ''})
```
Returns an error:
```
OSErrorTraceback (most recent call last)
<ipython-input-38-8e99becd757f> in <module>()
      4 helpstring = subprocess.check_output(['gnuplot', '--help'],
      5                                         stderr=subprocess.STDOUT,
----> 6                                         env={'DISPLAY': ''})
      7 
      8 

/Users/nils/miniconda3/envs/py27/lib/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    214     if 'stdout' in kwargs:
    215         raise ValueError('stdout argument not allowed, it will be overridden.')
--> 216     process = Popen(stdout=PIPE, *popenargs, **kwargs)
    217     output, unused_err = process.communicate()
    218     retcode = process.poll()

/Users/nils/miniconda3/envs/py27/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    392                                 p2cread, p2cwrite,
    393                                 c2pread, c2pwrite,
--> 394                                 errread, errwrite)
    395         except Exception:
    396             # Preserve original exception in case os.close raises.

/Users/nils/miniconda3/envs/py27/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1045                         raise
   1046                 child_exception = pickle.loads(data)
-> 1047                 raise child_exception
   1048 
   1049 

OSError: [Errno 2] No such file or directory
```
It works with a hard coded path:
```
import subprocess
import re

helpstring = subprocess.check_output(['/usr/local/bin/gnuplot', '--help'],
                                        stderr=subprocess.STDOUT,
                                        env={'DISPLAY': ''})
print(helpstring)
```
Returns:
```
Usage: gnuplot [OPTION] ... [FILE]
  -V, --version
  -h, --help
  -p  --persist
  -d  --default-settings
  -c  scriptfile ARG1 ARG2 ... 
  -e  "command1; command2; ..."
gnuplot 5.2 patchlevel 3
```
It think that subprocess is somehow not able to read $PATH, since /usr/local/bin is on it...
```
echo $PATH | grep -o "/usr/local/bin"
/usr/local/bin
```
It would be nice to have function for defining the path of gnuplot, but nevertheless it's actually a problem of subprocess not being able to read $PATH.

**Comment by awhillas** [comment] 2018-08-09 09:40
Agh :@
This is stopping me using it with Jupyter notebooks :(

**Comment by dkogan** [comment] 2018-08-10 05:03
This isn't stopping you from doing anything. You can hard-code the path you want. Or, you know, you can use a distro that actually has gnuplot in their repos.

I'm closing this issue. It has nothing to do with THIS project. Is it this: https://bugs.python.org/issue8557 ? If somebody knows what the issue is, and wants to propose a patch, please do. Otherwise, I don't know what I can do here. This works just fine on reasonable OSs.

**Closed by dkogan** 2018-08-10 05:03 UTC

**Comment by josh2d2** [comment] 2018-09-07 17:28
Disappointing closure.  

I tested this changed code below on OSX and it got me past similar issues in importing the module -- I've not yet actually utilized the library yet.  I suspect similar subprocess calls will need to be corrected/altered? 
I dont know if its truly necessary to pass a completely clean environment to gnuplot, but in this change I just capture the parent environment (which has the PATH correctly set) and clear the DISPLAY variable..

```python
def _getGnuplotFeatures():

    # Be careful talking to gnuplot here. If you use a tty then gnuplot messes
    # with the tty settings where it should NOT. For example it turns on the
    # local echo. So make sure to not use a tty. Furthermore, I turn off the
    # DISPLAY. I'm not actually plotting anything, so a DISPLAY can try to
    # X-forward and be really slow pointlessly

    # first, I run 'gnuplot --help' to extract all the cmdline options as features
    sub_env = os.environ.copy()
    sub_env['DISPLAY'] = '' 
    helpstring = subprocess.check_output(['gnuplot', '--help'],
                                         stderr=subprocess.STDOUT,
                                         env=sub_env).decode()

```

**Comment by josh2d2** [comment] 2018-09-07 17:34
Oh, with just that change, it does seem that gnuplotlib is able to function...
I recommend this get reopened and someone make a patch/fix. 

```
In [1]: import gnuplotlib as gp

In [2]: import numpy as np

In [3]:

In [3]: x = np.linspace(-5,5,100)

In [4]: gp.plot( x, np.sin(x) )

In [5]: gp.plot( (x, np.sin(x), {'with': 'boxes'}),
   ...: ...          (x, np.cos(x), {'legend': 'cosine'}),
   ...:
   ...: ...          _with    = 'lines',
   ...: ...          terminal = 'dumb 80,40',
   ...: ...          unset    = 'grid')


    1 +---------------------------------------------------------------------+
      |     ***** +          +         ##+##   *******          +           |
      |     ******                    #     #  *******       cosine ####### |
      |     ******                    #     # *********                     |
  0.8 |-+   *******                  #       #**********                  +-|
      |     *******                  #       #**********                    |
      |     ********                #        *#*********                    |
  0.6 |-+   ********                #        **#*********                 +-|
      |     ********               #         **#*********                   |
      |     *********              #        ***#*********                   |
      |     *********              #       *****#*********                  |
  0.4 |-+   *********             #        *****#*********                +-|
      |     **********            #        *****#*********                  |
      |     #*********            #        *****#**********           #     |
  0.2 |-+   #**********          #        *******#*********           #   +-|
      |     #**********          #        ********#*********          #     |
      |     *#*********         #         ********#*********         #      |
      |     **#*********        #        *********#*********         #      |
    0 |-+   **#*****************#*****************#*****************#**   +-|
      |       #        *********#*********         #       *********#**     |
      |       #        ********#*********          #        ********#**     |
      |        #       ********#*********          #        ********#**     |
 -0.2 |-+      #        *******#*********          #        *******#***   +-|
      |        #        ******#*********            #        ******#***     |
      |        #         *****#*********            #        ******#***     |
 -0.4 |-+       #        *****#*********            #         ****#****   +-|
      |          #       *****#*********             #        ****#****     |
      |          #        ***#*********              #        ***#*****     |
      |          #        **#*********                #        **#*****     |
 -0.6 |-+         #       **#*********                #        **#*****   +-|
      |           #        *#*********                #        *#******     |
      |           #        #*********                  #        #******     |
 -0.8 |-+          #       #*********                  #       #*******   +-|
      |            #      # *********                   #      # ******     |
      |             #    #   *******                     #    #  ******     |
      |           +  #  ##   *******     +           +   ##  #  + *****     |
   -1 +---------------------------------------------------------------------+
     -6          -4         -2           0           2          4           6
```

**Comment by dkogan** [comment] 2018-09-07 17:37
Hi. I'd love to get this fixed, but as far as I can tell, this isn't an issue on free-software distros. So I can't see this problem. Do you understand what the problem is, and do you have a proposed fix?

**Comment by dkogan** [comment] 2018-09-07 17:42
Oh, I see. Was the issue that the subprocess calls weren't inheriting the environment from the parent python process, so the custom PATH wasn't being used? Is it sufficient to explicitly pass down a copy of os.environ (like you did above) to the subprocess calls? If that is done, does it make your problem go away?

**Comment by dkogan** [comment] 2018-09-07 18:11
I just ran some tests, and indeed I had a bug. Thanks for pestering me. I THINK I fixed it just now. Can you please confirm that things work with the code just pushed to master?
